' Developer Express Code Central Example:
' How to serialize custom properties with a custom type using the CreateContentPropertyValue event
' 
' This example demonstrates how to serialize and deserialize custom properties
' with a custom type. If a custom property is null when the deserialization
' process is invoked, it's necessary to handle the
' DXSerializer.CreateContentPropertyValue event. In the CreateContentPropertyValue
' event handler, create a new instance of a custom type and assign it to the
' XtraCreateContentPropertyValueEventArgs.SomeCustomProperty property.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=T159099

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My


    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")> _
    Friend NotInheritable Partial Class Settings
        Inherits System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As Settings = (CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

        Public Shared ReadOnly Property [Default]() As Settings
            Get
                Return defaultInstance
            End Get
        End Property
    End Class
End Namespace
